-- SafeNight Snowflake Database Schema
-- Run these commands in the Snowflake console to set up the database

-- Create database and schema
CREATE DATABASE IF NOT EXISTS SAFENIGHT_DB;
USE DATABASE SAFENIGHT_DB;
CREATE SCHEMA IF NOT EXISTS APP_DATA;
USE SCHEMA APP_DATA;

-- Users table
CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    WEIGHT NUMBER,
    GENDER VARCHAR(10),
    SOS_CODE_WORD VARCHAR(50),
    SETTINGS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Emergency Contacts
CREATE TABLE IF NOT EXISTS EMERGENCY_CONTACTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    RELATIONSHIP VARCHAR(50)
);

-- Drinks (for drink history)
CREATE TABLE IF NOT EXISTS DRINKS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    NAME VARCHAR(100),
    ALCOHOL_TYPE VARCHAR(20),
    ESTIMATED_OZ NUMBER(5,2),
    ESTIMATED_ABV NUMBER(4,3),
    LOGGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Venues (for geo-queries)
CREATE TABLE IF NOT EXISTS VENUES (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(200),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    TYPE VARCHAR(50),
    SAFETY_RATING NUMBER(2,1)
);

-- Night Plans
CREATE TABLE IF NOT EXISTS NIGHT_PLANS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    TITLE VARCHAR(200),
    DEPARTURE_TIME TIMESTAMP_NTZ,
    RETURN_TIME TIMESTAMP_NTZ,
    TRANSPORTATION VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'draft',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- SOS Events
CREATE TABLE IF NOT EXISTS SOS_EVENTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    TRIGGER_TYPE VARCHAR(20),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    ADDRESS VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'active',
    BLOCKCHAIN_HASH VARCHAR(128),
    BLOCKCHAIN_SIGNATURE VARCHAR(256),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT TIMESTAMP_NTZ
);

-- Direct Messages
CREATE TABLE IF NOT EXISTS MESSAGES (
    ID VARCHAR(36) PRIMARY KEY,
    CONVERSATION_ID VARCHAR(73) NOT NULL,
    SENDER_ID VARCHAR(36) REFERENCES USERS(ID),
    RECEIVER_ID VARCHAR(36) REFERENCES USERS(ID),
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    READ_AT TIMESTAMP_NTZ
);

-- Ride Requests (shared between all users)
CREATE TABLE IF NOT EXISTS RIDE_REQUESTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    USER_DISPLAY_NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,  -- 'need_ride' or 'offer_ride'
    FROM_LOCATION VARCHAR(200) NOT NULL,
    TO_LOCATION VARCHAR(200) NOT NULL,
    DEPARTURE_TIME TIMESTAMP_NTZ NOT NULL,
    MAX_PASSENGERS NUMBER,
    STATUS VARCHAR(20) DEFAULT 'open',  -- 'open', 'matched', 'completed', 'cancelled'
    MATCHED_WITH VARCHAR(36),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Note: Snowflake standard tables don't support CREATE INDEX
-- Snowflake uses automatic micro-partitioning for query optimization
-- For better performance on large tables, consider using clustering keys:
-- ALTER TABLE USERS CLUSTER BY (EMAIL);
-- ALTER TABLE MESSAGES CLUSTER BY (CONVERSATION_ID, CREATED_AT);
